<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => false,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'facebook/graph-sdk' => array(
            'pretty_version' => '5.7.0',
            'version' => '5.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facebook/graph-sdk',
            'aliases' => array(),
            'reference' => '2d8250638b33d73e7a87add65f47fabf91f8ad9b',
            'dev_requirement' => false,
        ),
        'facebook/php-ads-sdk' => array(
            'pretty_version' => '2.8.2',
            'version' => '2.8.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facebook/php-ads-sdk',
            'aliases' => array(),
            'reference' => 'd51193b19d730ae9274d45540986e1ac311b074d',
            'dev_requirement' => false,
        ),
        'facebook/php-business-sdk' => array(
            'pretty_version' => '5.0.5',
            'version' => '5.0.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facebook/php-business-sdk',
            'aliases' => array(),
            'reference' => '8cee442e8b587428e4520fd554f93658a34408d4',
            'dev_requirement' => false,
        ),
    ),
);
